distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:40863'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:42531'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:46609'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:33357'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:45947'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:42189'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:44141'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:33159'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:44197'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:41713'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:38813'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:47003'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:41873'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:36637'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:36083'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:45001'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:34007'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:37319'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:44473'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:43455'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:46623'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:34037'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:43091'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:44837'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:38173'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:39339'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:35053'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:38823'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:39601'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:35095'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:38617'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:45715'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:45769'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:45113'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:41953'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:34705'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:33523'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:45041'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:40023'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:36357'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:43757'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:37247'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:39477'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:33587'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:35225'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:45919'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:34709'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:38297'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:33029'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:33079'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:44801'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:42771'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:43765'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:41757'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:36173'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:34507'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:39073'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:45869'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:38511'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:35107'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:37719'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:42769'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:46175'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:42015'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:41493'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:40793'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:43795'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:38771'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:43187'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:41203'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:46033'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:39693'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:35587'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:34339'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:41285'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:37321'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:33689'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:43385'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:39953'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:42609'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:43599'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:34343'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:41515'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:46189'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:39315'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:43437'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:38561'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:42827'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:37525'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:36827'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:33139'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:41563'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:35703'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:41347'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:35457'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:34651'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:46915'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:42449'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:42907'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.246:39267'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66395 exited with status 1
distributed.nanny - INFO - Worker process 66401 exited with status 1
distributed.nanny - INFO - Worker process 66443 exited with status 1
distributed.nanny - INFO - Worker process 66423 exited with status 1
distributed.nanny - INFO - Worker process 66435 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66403 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66406 exited with status 1
distributed.nanny - INFO - Worker process 66415 exited with status 1
distributed.nanny - INFO - Worker process 66433 exited with status 1
distributed.nanny - INFO - Worker process 66422 exited with status 1
distributed.nanny - INFO - Worker process 66429 exited with status 1
distributed.nanny - INFO - Worker process 66445 exited with status 1
distributed.nanny - INFO - Worker process 66417 exited with status 1
distributed.nanny - INFO - Worker process 66427 exited with status 1
distributed.nanny - INFO - Worker process 66461 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66447 exited with status 1
distributed.nanny - INFO - Worker process 66409 exited with status 1
distributed.nanny - INFO - Worker process 66412 exited with status 1
distributed.nanny - INFO - Worker process 66451 exited with status 1
distributed.nanny - INFO - Worker process 66394 exited with status 1
distributed.nanny - INFO - Worker process 66456 exited with status 1
distributed.nanny - INFO - Worker process 66454 exited with status 1
distributed.nanny - INFO - Worker process 66398 exited with status 1
distributed.nanny - INFO - Worker process 66439 exited with status 1
distributed.nanny - INFO - Worker process 66463 exited with status 1
distributed.nanny - INFO - Worker process 66469 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:40863'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:42531'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:33357'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:45947'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:46609'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:42189'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:44141'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:33159'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:44197'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:41713'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:47003'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:38813'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:41873'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:36637'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:36083'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:45001'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:34007'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:37319'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:44473'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:43455'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:46623'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:34037'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:43091'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:38173'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:44837'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:35053'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66475 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 66466 exited with status 1
distributed.nanny - INFO - Worker process 66580 exited with status 1
distributed.nanny - INFO - Worker process 66624 exited with status 1
distributed.nanny - INFO - Worker process 66488 exited with status 1
distributed.nanny - INFO - Worker process 66560 exited with status 1
distributed.nanny - INFO - Worker process 66642 exited with status 1
distributed.nanny - INFO - Worker process 66576 exited with status 1
distributed.nanny - INFO - Worker process 66649 exited with status 1
distributed.nanny - INFO - Worker process 66631 exited with status 1
distributed.nanny - INFO - Worker process 66621 exited with status 1
distributed.nanny - INFO - Worker process 66527 exited with status 1
distributed.nanny - INFO - Worker process 66481 exited with status 1
distributed.nanny - INFO - Worker process 66602 exited with status 1
distributed.nanny - INFO - Worker process 66585 exited with status 1
distributed.nanny - INFO - Worker process 66599 exited with status 1
distributed.nanny - INFO - Worker process 66568 exited with status 1
distributed.nanny - INFO - Worker process 66563 exited with status 1
distributed.nanny - INFO - Worker process 66611 exited with status 1
distributed.nanny - INFO - Worker process 66623 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 66486 exited with status 1
distributed.nanny - INFO - Worker process 66508 exited with status 1
distributed.nanny - INFO - Worker process 66495 exited with status 1
distributed.nanny - INFO - Worker process 66511 exited with status 1
distributed.nanny - INFO - Worker process 66514 exited with status 1
distributed.nanny - INFO - Worker process 66473 exited with status 1
distributed.nanny - INFO - Worker process 66535 exited with status 1
distributed.nanny - INFO - Worker process 66523 exited with status 1
distributed.nanny - INFO - Worker process 66502 exited with status 1
distributed.nanny - INFO - Worker process 66521 exited with status 1
distributed.nanny - INFO - Worker process 66541 exited with status 1
distributed.nanny - INFO - Worker process 66539 exited with status 1
distributed.nanny - INFO - Worker process 66557 exited with status 1
distributed.nanny - INFO - Worker process 66549 exited with status 1
distributed.nanny - INFO - Worker process 66589 exited with status 1
distributed.nanny - INFO - Worker process 66614 exited with status 1
distributed.nanny - INFO - Worker process 66647 exited with status 1
distributed.nanny - INFO - Worker process 66633 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66596 exited with status 1
distributed.nanny - INFO - Worker process 66498 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66477 exited with status 1
distributed.nanny - INFO - Worker process 66553 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66593 exited with status 1
distributed.nanny - INFO - Worker process 66515 exited with status 1
distributed.nanny - INFO - Worker process 66532 exited with status 1
distributed.nanny - INFO - Worker process 66609 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66617 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66571 exited with status 1
distributed.nanny - INFO - Worker process 66565 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66545 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66582 exited with status 1
distributed.nanny - INFO - Worker process 66679 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66605 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66639 exited with status 1
distributed.nanny - INFO - Worker process 66657 exited with status 1
distributed.nanny - INFO - Worker process 66637 exited with status 1
distributed.nanny - INFO - Worker process 66651 exited with status 1
distributed.nanny - INFO - Worker process 66672 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 66669 exited with status 1
distributed.nanny - INFO - Worker process 66654 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:39339'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:39601'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:38823'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:35095'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:38617'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:45769'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:45715'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:45113'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:41953'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:34705'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:33523'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:45041'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:40023'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:36357'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:43757'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:37247'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:39477'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:33587'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:35225'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:34709'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:45919'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:38297'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:33029'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:33079'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:44801'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:42771'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:43765'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:41757'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:36173'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:34507'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:39073'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:35107'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:45869'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:38511'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:37719'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:42769'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:46175'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:42015'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:41493'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:43795'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:38771'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:40793'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:43187'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:41203'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:39693'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:35587'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:46033'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:41285'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:34339'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:33689'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:37321'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:43385'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:42609'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:39953'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:43599'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:34343'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:41515'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:43437'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:38561'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:37525'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 66694 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 66660 exited with status 1
distributed.nanny - INFO - Worker process 66663 exited with status 1
distributed.nanny - INFO - Worker process 66676 exited with status 1
distributed.nanny - INFO - Worker process 66696 exited with status 1
distributed.nanny - INFO - Worker process 66702 exited with status 1
distributed.nanny - INFO - Worker process 66691 exited with status 1
distributed.nanny - INFO - Worker process 66698 exited with status 1
distributed.nanny - INFO - Worker process 66688 exited with status 1
distributed.nanny - INFO - Worker process 66705 exited with status 1
distributed.nanny - INFO - Worker process 66686 exited with status 1
distributed.nanny - INFO - Worker process 66700 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 66682 exited with status 1
distributed.nanny - INFO - Worker process 66684 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:46189'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:39315'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:42827'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:41563'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:36827'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:35703'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:33139'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:41347'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:35457'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:34651'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:46915'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:42449'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:42907'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.246:39267'
distributed.dask_worker - INFO - End worker
