distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:36929'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:38493'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:38183'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:42241'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:43365'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:35077'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:43915'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:44965'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:38417'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:39311'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:44559'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:45109'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:42765'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:45703'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:37705'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:46957'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:45947'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:40273'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34875'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:42351'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:42987'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:41067'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:37979'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:40351'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:45241'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:42705'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:38843'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:40845'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:36401'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:45071'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:39153'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:37975'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:32843'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34443'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:42943'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:42087'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:46161'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:38869'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:36345'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34015'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34701'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:35051'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:38605'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:33327'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34851'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34389'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:37951'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:47015'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:45431'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:36573'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:42281'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34919'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:39215'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:44141'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:42707'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:37145'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:42815'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:45277'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:43903'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:46853'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:40221'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:40061'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:41095'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:32871'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:32935'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:43663'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:33769'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:33551'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34657'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34135'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:44753'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:36215'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34357'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34089'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:33425'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:39503'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:41651'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:33557'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:39981'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:40383'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:45573'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:37943'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:37939'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:36953'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:34519'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:43443'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:46699'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:41375'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:43731'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:41455'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:47087'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:40907'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:37165'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:43953'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:46881'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:46657'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:32999'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:42793'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:37081'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.218:37655'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 64774 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 64773 exited with status 1
distributed.nanny - INFO - Worker process 64778 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:36929'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:43365'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:38493'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 64777 exited with status 1
distributed.nanny - INFO - Worker process 64794 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:38183'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:38417'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 64782 exited with status 1
distributed.nanny - INFO - Worker process 64788 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:42241'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:35077'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 64797 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 64785 exited with status 1
distributed.nanny - INFO - Worker process 64790 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:43915'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:44965'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:39311'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 64930 exited with status 1
distributed.nanny - INFO - Worker process 64921 exited with status 1
distributed.nanny - INFO - Worker process 64845 exited with status 1
distributed.nanny - INFO - Worker process 64826 exited with status 1
distributed.nanny - INFO - Worker process 64903 exited with status 1
distributed.nanny - INFO - Worker process 64937 exited with status 1
distributed.nanny - INFO - Worker process 64857 exited with status 1
distributed.nanny - INFO - Worker process 64854 exited with status 1
distributed.nanny - INFO - Worker process 65039 exited with status 1
distributed.nanny - INFO - Worker process 64907 exited with status 1
distributed.nanny - INFO - Worker process 65049 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 64851 exited with status 1
distributed.nanny - INFO - Worker process 64952 exited with status 1
distributed.nanny - INFO - Worker process 65005 exited with status 1
distributed.nanny - INFO - Worker process 64867 exited with status 1
distributed.nanny - INFO - Worker process 64999 exited with status 1
distributed.nanny - INFO - Worker process 64909 exited with status 1
distributed.nanny - INFO - Worker process 64992 exited with status 1
distributed.nanny - INFO - Worker process 65051 exited with status 1
distributed.nanny - INFO - Worker process 64833 exited with status 1
distributed.nanny - INFO - Worker process 64915 exited with status 1
distributed.nanny - INFO - Worker process 64966 exited with status 1
distributed.nanny - INFO - Worker process 64823 exited with status 1
distributed.nanny - INFO - Worker process 64925 exited with status 1
distributed.nanny - INFO - Worker process 65030 exited with status 1
distributed.nanny - INFO - Worker process 64818 exited with status 1
distributed.nanny - INFO - Worker process 64848 exited with status 1
distributed.nanny - INFO - Worker process 64836 exited with status 1
distributed.nanny - INFO - Worker process 64918 exited with status 1
distributed.nanny - INFO - Worker process 65020 exited with status 1
distributed.nanny - INFO - Worker process 64953 exited with status 1
distributed.nanny - INFO - Worker process 64939 exited with status 1
distributed.nanny - INFO - Worker process 64971 exited with status 1
distributed.nanny - INFO - Worker process 65013 exited with status 1
distributed.nanny - INFO - Worker process 64961 exited with status 1
distributed.nanny - INFO - Worker process 65058 exited with status 1
distributed.nanny - INFO - Worker process 64872 exited with status 1
distributed.nanny - INFO - Worker process 64864 exited with status 1
distributed.nanny - INFO - Worker process 64942 exited with status 1
distributed.nanny - INFO - Worker process 64950 exited with status 1
distributed.nanny - INFO - Worker process 65066 exited with status 1
distributed.nanny - INFO - Worker process 64812 exited with status 1
distributed.nanny - INFO - Worker process 65062 exited with status 1
distributed.nanny - INFO - Worker process 64889 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 64957 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34851'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34389'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:37951'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:45431'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:36573'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:42281'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:39215'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:44141'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:42707'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:42815'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:40221'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:41095'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:32935'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:33769'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34089'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:39503'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:33557'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:45573'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:43443'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:43731'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:40907'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:37165'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:37705'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:45947'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34875'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:42351'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:41067'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:37979'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:42705'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:38843'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:40845'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:36401'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:45071'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:37975'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:32843'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 64830 exited with status 1
distributed.nanny - INFO - Worker process 64924 exited with status 1
distributed.nanny - INFO - Worker process 64882 exited with status 1
distributed.nanny - INFO - Worker process 64803 exited with status 1
distributed.nanny - INFO - Worker process 65017 exited with status 1
distributed.nanny - INFO - Worker process 64840 exited with status 1
distributed.nanny - INFO - Worker process 64815 exited with status 1
distributed.nanny - INFO - Worker process 64967 exited with status 1
distributed.nanny - INFO - Worker process 64809 exited with status 1
distributed.nanny - INFO - Worker process 64989 exited with status 1
distributed.nanny - INFO - Worker process 64800 exited with status 1
distributed.nanny - INFO - Worker process 64973 exited with status 1
distributed.nanny - INFO - Worker process 64982 exited with status 1
distributed.nanny - INFO - Worker process 64820 exited with status 1
distributed.nanny - INFO - Worker process 64876 exited with status 1
distributed.nanny - INFO - Worker process 64883 exited with status 1
distributed.nanny - INFO - Worker process 65022 exited with status 1
distributed.nanny - INFO - Worker process 64879 exited with status 1
distributed.nanny - INFO - Worker process 65054 exited with status 1
distributed.nanny - INFO - Worker process 64806 exited with status 1
distributed.nanny - INFO - Worker process 65036 exited with status 1
distributed.nanny - INFO - Worker process 64842 exited with status 1
distributed.nanny - INFO - Worker process 64866 exited with status 1
distributed.nanny - INFO - Worker process 64861 exited with status 1
distributed.nanny - INFO - Worker process 64984 exited with status 1
distributed.nanny - INFO - Worker process 65064 exited with status 1
distributed.nanny - INFO - Worker process 64912 exited with status 1
distributed.nanny - INFO - Worker process 65060 exited with status 1
distributed.nanny - INFO - Worker process 64987 exited with status 1
distributed.nanny - INFO - Worker process 64979 exited with status 1
distributed.nanny - INFO - Worker process 65043 exited with status 1
distributed.nanny - INFO - Worker process 65025 exited with status 1
distributed.nanny - INFO - Worker process 64891 exited with status 1
distributed.nanny - INFO - Worker process 65046 exited with status 1
distributed.nanny - INFO - Worker process 65008 exited with status 1
distributed.nanny - INFO - Worker process 64896 exited with status 1
distributed.nanny - INFO - Worker process 64893 exited with status 1
distributed.nanny - INFO - Worker process 64900 exited with status 1
distributed.nanny - INFO - Worker process 64946 exited with status 1
distributed.nanny - INFO - Worker process 64934 exited with status 1
distributed.nanny - INFO - Worker process 65028 exited with status 1
distributed.nanny - INFO - Worker process 65032 exited with status 1
distributed.nanny - INFO - Worker process 65001 exited with status 1
distributed.nanny - INFO - Worker process 65056 exited with status 1
distributed.nanny - INFO - Worker process 65012 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:42943'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:42087'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:46161'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:36345'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:38869'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34015'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34701'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:38605'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:35051'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:33327'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:47015'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34919'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:37145'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:45277'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:43903'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:46853'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:40061'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:32871'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:43663'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:33551'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34135'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:44753'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34657'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:36215'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34357'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:33425'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:41651'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:40383'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:39981'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:37943'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:37939'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:36953'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34519'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:46699'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:41375'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:41455'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:47087'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:43953'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:46881'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:46657'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:32999'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:42793'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:37081'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:37655'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:44559'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:45109'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:42765'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:45703'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:46957'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:40273'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:42987'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:40351'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:45241'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:39153'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.218:34443'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.dask_worker - INFO - End worker
